apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: kube-system
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: fluent-bit
        image: kubeup/fluent-bit-aliyun:master
        imagePullPolicy: Always
        env:
          - name:  ALIYUN_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: fluent-bit-config
                key: ALIYUN_ACCESS_KEY
          - name:  ALIYUN_ACCESS_KEY_SECRET
            valueFrom:
              secretKeyRef:
                name: fluent-bit-config
                key: ALIYUN_ACCESS_KEY_SECRET
          - name:  ALIYUN_SLS_PROJECT
            valueFrom:
              secretKeyRef:
                name: fluent-bit-config
                key: ALIYUN_SLS_PROJECT
          - name:  ALIYUN_SLS_LOGSTORE
            valueFrom:
              secretKeyRef:
                name: fluent-bit-config
                key: ALIYUN_SLS_LOGSTORE
          - name:  ALIYUN_SLS_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: fluent-bit-config
                key: ALIYUN_SLS_ENDPOINT
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
